# Copyright cocotb contributors
# Copyright (c) 2015 Potential Ventures Ltd
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause


include ../../designs/sample_module/Makefile

COCOTB_TEST_MODULES = issue_142
