# Private CI trigger.  Used to run tooling that can't currently be shared
# publicly.

trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - "*"
pr:
  branches:
    include:
    - '*'

# The runner used for private CI enforces the use of the template below. All
# build steps need to be placed into the template.
resources:
  repositories:
  - repository: cocotb-private-ci
    type: github
    endpoint: cocotb
    name: cocotb/cocotb-private-ci

extends:
  template: jobs.yml@cocotb-private-ci
