# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# Codecov configuration
coverage:
    status:
        project:
            default:
                # Report a CI failure if coverage drops by more than 1 percent.
                threshold: 1%
