image:
  file: .gitpod.Dockerfile

tasks:
  - before: >
      pip3 install -e . &&
      export COCOTB_REDUCED_LOG_FMT=1
    init: >
      gp preview https://docs.cocotb.org/ &&
      cd /workspace/cocotb/examples/simple_dff &&
      gp open dff.sv &&
      gp open dff.vhdl &&
      gp open Makefile &&
      gp open test_dff.py &&
      make SIM=icarus &&
      EXTRA_ARGS="--trace-fst --trace-structs" make SIM=verilator &&
      gtkwave dump.fst --rcvar 'initial_window_x 1920' --rcvar 'initial_window_y 1061' --rcvar 'do_initial_zoom_fit yes' &
    command: >
      cd /workspace/cocotb/examples/simple_dff ;
      history -s make SIM=cvc ;
      history -s make SIM=ghdl TOPLEVEL_LANG=vhdl ;
      history -s make SIM=icarus ;
      history -s EXTRA_ARGS=\"--trace-fst --trace-structs\" make SIM=verilator ;
      history -s gtkwave dump.fst --rcvar \'initial_window_x 1920\' --rcvar \'initial_window_y 1061\' --rcvar \'do_initial_zoom_fit yes\' ;
      history -d 3

# NOTE: the geometry for gtkwave's fullscreen size can be found with xwininfo -root

# https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080  # VNC for e.g. gtkwave
    onOpen: notify
  - port: 5900
    onOpen: ignore

vscode:
  extensions:
    - mshr-h.veriloghdl@1.0.6:RPslnvyzniF7C66mxHT+Hg==
    - vhdlwhiz.vhdl-by-vhdlwhiz@1.2.10:fJXQenGkzoZwUN/RddpuSw==
