# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

python:
  version: 3.8
  install:
    - requirements: documentation/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: documentation/source/conf.py
