# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

MODULE := test_forked_exception

include ../../designs/sample_module/Makefile
