# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

all:
	pytest -s

clean:
	rm -rf sim_build/
	rm -f results.xml
