# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

all:
	@echo "Always skip this directory. Relevant tests are in test_3316_[a-d] directories."
