###############################################################################
# Copyright (c) 2013, 2018 Potential Ventures Ltd
# Copyright (c) 2013 SolarFlare Communications Inc
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Potential Ventures Ltd,
#       SolarFlare Communications Inc nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL POTENTIAL VENTURES LTD BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
###############################################################################

# This is a simple wrapper Makefile to build appropriate libraries

COCOTB_SHARE_MAKEFILES_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
COCOTB_SHARE_DIR := $(abspath $(COCOTB_SHARE_MAKEFILES_DIR)/..)
export COCOTB_SHARE_DIR

all-libs: cocotb-libs cocotb-vpi-libs cocotb-vhpi-libs cocotb-fli-libs

vpi-libs : cocotb-libs cocotb-vpi-libs

#SIM_BUILD ?= sim_build
#export SIM_BUILD

# Default to Icarus if no simulator is defined
SIM ?= icarus

USER_DIR ?= $(shell pwd)
export USER_DIR

include $(COCOTB_SHARE_DIR)/lib/Makefile

cocotb-libs : $(COCOTB_LIBS) 

cocotb-vpi-libs : $(COCOTB_VPI_LIB)

cocotb-vhpi-libs : $(COCOTB_VHPI_LIB)

cocotb-fli-libs : $(COCOTB_FLI_LIB)

