# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

ifdef VERILATOR_TRACE
    $(warning VERILATOR_TRACE is deprecated, see the "Simulator Support" section in the documentation.)
endif

ifeq ($(SIM_LOWERCASE),aldec)
    $(warning Using SIM=aldec is deprecated, please use SIM=riviera instead.)
    SIM_LOWERCASE := riviera
endif
