# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# select only y_tests from all MODULEs

include ../../designs/sample_module/Makefile

COCOTB_TEST_MODULES := x_tests
export COCOTB_TEST_FILTER := y_test
