# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

include ../../designs/defaultless_parameter_module/Makefile

MODULE = test_defaultless_parameter
