
TOPLEVEL := gpio_top

VERILOG_SOURCES = $(COCOTB)/tests/designs/gpio_wbc/src/gpio_top.v

COMPILE_ARGS += -I $(COCOTB)/tests/designs/gpio_wbc/src/

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
