# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# test COCOTB_TEST_MODULES contains a multi-level Python module path, separated by period

COCOTB_TEST_MODULES = test_package.test_module_path

export PYTHONPATH := .

include ../../designs/sample_module/Makefile
