# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# test MODULE contains a multi-level Python module path, separated by period

MODULE = test_package.test_module_path

export PYTHONPATH := .

include ../../designs/sample_module/Makefile
