# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

CURRENT_DIR := $(shell dirname $(abspath $(lastword $(MAKEFILE_LIST))))

TOPLEVEL_LANG ?= verilog
SIM ?= verilator

VERILOG_SOURCES := $(CURRENT_DIR)/test_verilator_timing.sv
COCOTB_TOPLEVEL := test_verilator_timing
