# Copyright cocotb contributors
# Copyright (c) 2013 Potential Ventures Ltd
# Copyright (c) 2013 SolarFlare Communications Inc
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

include ../../designs/plusargs_module/Makefile

COCOTB_PLUSARGS=+foo=bar +test1 +test2 +options=fubar +lol=wow=4

COCOTB_TEST_MODULES = plusargs
