# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

CMD_BIN := bpsim -nc
VHDL_COMP_BIN := bpvhcom
V_COMP_BIN := bpvlcom

ifdef BPSIM_BIN_DIR
    CMD := $(shell :; command -v $(BPSIM_BIN_DIR)/$(CMD_BIN) 2>/dev/null)
    VHDL_COMP = $(shell :; command -v $(BPSIM_BIN_DIR)/$(VHDL_COMP_BIN) 2>/dev/null)
    V_COMP = $(shell :; command -v $(BPSIM_BIN_DIR)/$(V_COMP_BIN) 2>/dev/null)
else
    # auto-detect bin dir from system path
    CMD := $(shell :; command -v $(CMD_BIN) 2>/dev/null)
    VHDL_COMP = $(shell :; command -v $(VHDL_COMP_BIN) 2>/dev/null)
    V_COMP = $(shell :; command -v $(V_COMP_BIN) 2>/dev/null)
endif

ifneq ($(TOPLEVEL_LANG),verilog)

$(COCOTB_RESULTS_FILE):
	@echo "Skipping simulation as only Verilog top level is supported on simulator=$(SIM)"

else

ifeq (, $(CMD))
    $(error Unable to locate command >$(CMD_BIN)<)
endif

ifdef WAVES
#    WAVE_ARG := -waves $(WAVES)
WAVE_ARG := -waves $(SIM_BUILD)/$(COCOTB_TOPLEVEL).vcd
else
    WAVE_ARG :=
endif

ifneq ($(VHDL_SOURCES),)
	SV = -sv
endif

#------------------------------------------------------------------------------------
#------------- Setting Flag for Verilog/VHDL Precompiled Librares -------------------
#------------------------------------------------------------------------------------
ifneq ($(filter PATH_PRECOMPILED_LIB_%,$(.VARIABLES)),)
    PRECOMPILED_LIBS := 1
endif

#------------------------------------------------------------------------------------
#------------- Setting Flag for Verilog/VHDL Library Compile ------------------------
#------------------------------------------------------------------------------------
ifneq ($(filter VERILOG_SOURCES_%,$(.VARIABLES)),)
    VERILOG_LIB_COMPILE := 1
endif

ifneq ($(filter VHDL_SOURCES_%,$(.VARIABLES)),)
    VHDL_LIB_COMPILE := 1
endif

#------------------------------------------------------------------------------------
# Generate -L args for all VHDL and Verilog libraries compiled by cocotb, for elaboration and run.
#------------------------------------------------------------------------------------
LIB_SEARCH_ARGS  = $(foreach LIB, $(VHDL_LIB_ORDER),    -L $(LIB))
LIB_SEARCH_ARGS += $(foreach LIB, $(VERILOG_LIB_ORDER), -L $(LIB))
LIB_SEARCH_ARGS += $(foreach LIB, $(PRECOMPILED_LIB_LIST), -L $(LIB))

#------------------------------------------------------------------------------------
#-------------- Setting Flag for Verilog/VHDL Design Compile ------------------------
#------------------------------------------------------------------------------------
ifneq ($(VERILOG_SOURCES),)
    VERILOG_DESIGN_COMPILE := 1
endif

ifneq ($(VHDL_SOURCES),)
    VHDL_DESIGN_COMPILE := 1
endif

#------------------------------------------------------------------------------------
#-------------- Setting Flag for Verilog/VHDL Global Signal ------------------------
#------------------------------------------------------------------------------------
ifneq ($(VERILOG_GLOBAL_SIGNAL_SOURCE),)
    VERILOG_GLBL_SIG_COMPILE := 1
endif


#====================================================================================
WORK = work.
ifdef TOPLEVEL_LIBRARY
    BPSIM_WORK = $(TOPLEVEL_LIBRARY)
else
    BPSIM_WORK = bpsim_work
endif


TOPMODULE_ARG = -top $(WORK)$(call deprecate,TOPLEVEL,COCOTB_TOPLEVEL)
ifneq ($(VERILOG_GLOBAL_SIGNAL_SOURCE),)
  VER_GLBL_SIG_ARG = -top $(WORK)$(VERILOG_GLOBAL_SIGNAL_NAME)
endif

COMMON_ARGS = -nc -l bpsim.log

BPSIM_ARGS = $(COMMON_ARGS) -work $(SIM_BUILD)/$(BPSIM_WORK) -pli_lib $(shell cocotb-config --lib-name-path vpi bpsim) -lib work +acc+rwcbfsWF

VER_COMP_ARGS = $(COMMON_ARGS) $(SV) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)

ifdef VERILOG_INCLUDE_DIRS
    VER_COMP_ARGS += $(addprefix +incdir+, $(VERILOG_INCLUDE_DIRS))
endif

ifdef VERILOG_SEARCH_DIRS
    VER_SEARCH_ARGS = $(addprefix -y , $(VERILOG_SEARCH_DIRS))
    VER_COMP_ARGS  += $(VER_SEARCH_ARGS) +libext+.v+.sv 
endif
GENIMAGE_ARGS = $(COMMON_ARGS) -work $(SIM_BUILD)/$(BPSIM_WORK) -genimage image $(LIB_SEARCH_ARGS) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)

RUN_ARGS = $(BPSIM_ARGS) -image image $(LIB_SEARCH_ARGS) $(WAVE_ARG)
VHDL_COMP_ARGS = $(COMMON_ARGS) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)

#------------------------------------------------------------------------------------
#-------- Macro definitions for Verilog/VHDL Precompiled Libraries existence checks --
#------------------------------------------------------------------------------------
define CheckPreCompiledLibs
	$(foreach LIB, $(PRECOMPILED_LIB_LIST), \
		$(if $(PATH_PRECOMPILED_LIB_$(LIB)),,$(error PATH_PRECOMPILED_LIB_$(LIB)` is empty or undefined, but '$(LIB)' is present in PRECOMPILED_LIB_LIST)))
	$(foreach LIB_VAR, $(filter PRECOMPILED_LIB_LIST_%, $(.VARIABLES)), \
		$(eval _VLIB := $(patsubst PRECOMPILED_LIB_LIST_%,%,$(LIB_VAR))) \
		$(if $(filter $(_VLIB), $(PRECOMPILED_LIB_LIST)),,$(error $(_VLIB) has PATH_PRECOMPILED_LIB set but is not listed in PRECOMPILED_LIB_LIST)))
endef

#------------------------------------------------------------------------------------
#-------- Macro definitions for Verilog/VHDL Library source files existence checks --
#------------------------------------------------------------------------------------
define CheckVerilogLibSources
	$(foreach LIB, $(VERILOG_LIB_ORDER), \
		$(if $(VERILOG_SOURCES_$(LIB)),,$(error VERILOG_SOURCES_$(LIB) is empty or undefined, but '$(LIB)' is present in VERILOG_LIB_ORDER)))
	$(foreach SOURCES_VAR, $(filter VERILOG_SOURCES_%, $(.VARIABLES)), \
		$(eval _VLIB := $(patsubst VERILOG_SOURCES_%,%,$(SOURCES_VAR))) \
		$(if $(filter $(_VLIB), $(VERILOG_LIB_ORDER)),,$(error $(_VLIB) has VERILOG_SOURCES set but is not listed in VERILOG_LIB_ORDER)))
endef

define CheckVhdLibSources
	$(foreach LIB, $(VHDL_LIB_ORDER), \
		$(if $(VHDL_SOURCES_$(LIB)),,$(error VHDL_SOURCES_$(LIB) is empty or undefined, but '$(LIB)' is present in VHDL_LIB_ORDER)))
	$(foreach SOURCES_VAR, $(filter VHDL_SOURCES_%, $(.VARIABLES)), \
		$(eval _VLIB := $(patsubst VHDL_SOURCES_%,%,$(SOURCES_VAR))) \
		$(if $(filter $(_VLIB), $(VHDL_LIB_ORDER)),,$(error $(_VLIB) has VHDL_SOURCES set but is not listed in VHDL_LIB_ORDER)))
endef
#------------------------------------------------------------------------------------
#--------  Map precompiled external libraries  --------------------------------------
#------------------------------------------------------------------------------------
define MapPreCompiledLibs
	$(SIM_CMD_PREFIX) bplib -nc -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib $(LIB) $(PATH_PRECOMPILED_LIB_$(LIB))/$(LIB)
endef
#------------------------------------------------------------------------------------
#-------- Macro definitions for Verilog/VHDL Libraries Compile and Mapping ----------
#------------------------------------------------------------------------------------
# Compile a named VHDL library from VHDL_SOURCES_$(LIB) into $(SIM_BUILD)/$(LIB).
# Usage: $(foreach LIB, $(VHDL_LIB_ORDER), $(vhdl_CompileVhdLibs))
#
define CompileVerLibs
	$(SIM_CMD_PREFIX) $(V_COMP) -lib $(LIB) -work $(SIM_BUILD)/$(LIB) $(EXTRA_ARGS) $(VERILOG_SOURCES_$(LIB)) $(VER_COMP_ARGS)
endef

define MapVerLibs
	$(SIM_CMD_PREFIX) bplib -nc -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib $(LIB) $(SIM_BUILD)/$(LIB)
endef

define CompileVhdLibs
#        $(SIM_CMD_PREFIX) bplib -nc -work $(SIM_BUILD)/$(1) 
        $(foreach DEP,$(VHDL_LIB_DEPENDENCY_$(1)),$(call MapVhdDepLibs,$(1),$(DEP));)
	$(SIM_CMD_PREFIX) $(VHDL_COMP) $(VHDL_COMP_ARGS) -lib $(1) -work $(SIM_BUILD)/$(1) $(EXTRA_ARGS) $(VHDL_SOURCES_$(1))
endef

define MapVhdDepLibs
	$(SIM_CMD_PREFIX) bplib -nc -work $(SIM_BUILD)/$(1) map -lib $(2) $(SIM_BUILD)/$(2)
endef

define MapVhdLibs
	$(SIM_CMD_PREFIX) bplib -nc -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib $(LIB) $(SIM_BUILD)/$(LIB)
endef
#----------------------------------------------------------------------------------------------------

$(SIM_BUILD)/image.so: $(VHDL_SOURCES) $(VERILOG_SOURCES) $(CUSTOM_COMPILE_DEPS) | $(SIM_BUILD)

#------------------------------------------------------------------------------------
#------------------------------ Check PreCompiledLibs  ------------------------------
#------------------------------------------------------------------------------------
# Make sure all libs in VHDL_SOURCES_* are mentioned in VHDL_LIB_ORDER and vice versa
ifneq ($(PRECOMPILED_LIBS),)
	$(foreach LIB, $(PRECOMPILED_LIB_LIST), $(CheckPreCompiledLibs))
endif

#------------------------------------------------------------------------------------
#---------------------- Mapping Precompiled Libraries to work area ------------------
#------------------------------------------------------------------------------------
	$(foreach LIB, $(PRECOMPILED_LIB_LIST), $(MapPreCompiledLibs);)
	
#------------------------------------------------------------------------------------
#---------------------- VHDL IEEE Libraries to work area ----------------------------
#------------------------------------------------------------------------------------
	$(SIM_CMD_PREFIX) bplib -nc -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib ieee $(STD_LIBS)/ieee08

#------------------------------------------------------------------------------------
#--------------------------- Check VHDL_SOURCES_*  ------------------------------
#------------------------------------------------------------------------------------
# Make sure all libs in VHDL_SOURCES_* are mentioned in VHDL_LIB_ORDER and vice versa
ifneq ($(VHDL_LIB_COMPILE),)
	$(foreach LIB, $(VHDL_LIB_ORDER), $(CheckVhdLibSources))
endif

#------------------------------------------------------------------------------------------
#--------------------------- Check VERILOG_SOURCES_*  ---------------------------------
#------------------------------------------------------------------------------------------
# Make sure all libs in VERILOG_SOURCES_* are mentioned in VERILOG_LIB_ORDER and vice versa
ifneq ($(VERILOG_LIB_COMPILE),)
	$(foreach LIB, $(VERILOG_LIB_ORDER), $(CheckVerilogLibSources))
endif

#------------------------------------------------------------------------------------
#---------------------- Compiling and Mapping Vhdl Libraries ------------------------
#------------------------------------------------------------------------------------
ifneq ($(VHDL_LIB_COMPILE),)
	$(file > $(SIM_BUILD)/CompileVhdLibs.log, $(foreach LIB,$(VHDL_LIB_ORDER),$(call CompileVhdLibs,$(LIB))))
	$(foreach LIB,$(VHDL_LIB_ORDER),$(call CompileVhdLibs,$(LIB));)

endif
#------------------------------------------------------------------------------------
#---------------------- Mapping Vhdl Libraries to work area -------------------------
#------------------------------------------------------------------------------------
	$(foreach LIB, $(VHDL_LIB_ORDER), $(MapVhdLibs);)

#------------------------------------------------------------------------------------
#------------------- Compiling and Mapping Verilog Libraries ------------------------
#------------------------------------------------------------------------------------
ifneq ($(VERILOG_LIB_COMPILE),)
	$(file > $(SIM_BUILD)/CompileVerLibs.log, $(foreach LIB, $(VERILOG_LIB_ORDER), $(CompileVerLibs)))
	$(foreach LIB, $(VERILOG_LIB_ORDER), $(CompileVerLibs);)
endif
#------------------------------------------------------------------------------------
#------------- generate logfile for Mapping Verilog Libraries  ----------------------
#------------------------------------------------------------------------------------
ifneq ($(VERILOG_LIB_COMPILE),)
	$(file > $(SIM_BUILD)/MapVerLibs.log, $(foreach LIB, $(VERILOG_LIB_ORDER), $(MapVerLibs)))
	$(foreach LIB, $(VERILOG_LIB_ORDER), $(MapVerLibs);)
endif

ifneq ($(VHDL_SOURCES),)
	$(SIM_CMD_PREFIX) $(VHDL_COMP) $(VHDL_COMP_ARGS) -work $(SIM_BUILD)/$(BPSIM_WORK) $(EXTRA_ARGS) $(VHDL_SOURCES)
endif

ifneq ($(VERILOG_SOURCES),)
	$(SIM_CMD_PREFIX) $(V_COMP) -work $(SIM_BUILD)/$(BPSIM_WORK) $(EXTRA_ARGS) $(VERILOG_SOURCES) $(VER_COMP_ARGS)
endif

ifneq ($(VERILOG_GLOBAL_SIGNAL_SOURCE),)
	$(SIM_CMD_PREFIX) $(V_COMP) -work $(SIM_BUILD)/$(BPSIM_WORK) $(EXTRA_ARGS) $(VERILOG_GLOBAL_SIGNAL_SOURCE) $(VER_COMP_ARGS)
endif
#------------------------------------------------------------------------------------
#----------------------- generate image file image.so   -----------------------------
#------------------------------------------------------------------------------------
	$(file > $(SIM_BUILD)/GenImage.log, $(SIM_CMD_PREFIX) $(CMD) $(GENIMAGE_ARGS) $(TOPMODULE_ARG) $(VER_GLBL_SIG_ARG) $(EXTRA_ARGS))
	$(SIM_CMD_PREFIX) $(CMD) $(GENIMAGE_ARGS) $(TOPMODULE_ARG) $(VER_GLBL_SIG_ARG) $(EXTRA_ARGS)

GPI_USERS ?= $(shell cocotb-config --libpython);$(shell cocotb-config --pygpi-entry-point)
$(COCOTB_RESULTS_FILE): $(SIM_BUILD)/image.so $(CUSTOM_SIM_DEPS)
	$(RM) $(COCOTB_RESULTS_FILE)
	COCOTB_TEST_MODULES=$(call deprecate,MODULE,COCOTB_TEST_MODULES) \
	COCOTB_TESTCASE=$(call deprecate,TESTCASE,COCOTB_TESTCASE) \
	COCOTB_TEST_FILTER=$(COCOTB_TEST_FILTER) \
	COCOTB_TOPLEVEL=$(call deprecate,TOPLEVEL,COCOTB_TOPLEVEL) \
	GPI_EXTRA=$(GPI_EXTRA) \
	GPI_USERS="$(GPI_USERS)" \
	TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
	$(SIM_CMD_PREFIX) $(CMD) $(RUN_ARGS) $(TOPMODULE_ARG) $(VER_GLBL_SIG_ARG) $(EXTRA_ARGS)
	$(call check_results)

#------------------------------------------------------------------------------------
#--------------------- generate Simulation.log file    -----------------------------
#------------------------------------------------------------------------------------
	$(file > $(SIM_BUILD)/Simulation.log, $(SIM_CMD_PREFIX) $(CMD) $(RUN_ARGS) $(TOPMODULE_ARG) $(EXTRA_ARGS))
endif
