# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

CMD_BIN := bpsim
VHDL_COMP_BIN := bpvhcom
V_COMP_BIN := bpvlcom

ifdef BPSIM_BIN_DIR
    CMD := $(shell :; command -v $(BPSIM_BIN_DIR)/$(CMD_BIN) 2>/dev/null)
    VHDL_COMP = $(shell :; command -v $(BPSIM_BIN_DIR)/$(VHDL_COMP_BIN) 2>/dev/null)
    V_COMP = $(shell :; command -v $(BPSIM_BIN_DIR)/$(V_COMP_BIN) 2>/dev/null)
else
    # auto-detect bin dir from system path
    CMD := $(shell :; command -v $(CMD_BIN) 2>/dev/null)
    VHDL_COMP = $(shell :; command -v $(VHDL_COMP_BIN) 2>/dev/null)
    V_COMP = $(shell :; command -v $(V_COMP_BIN) 2>/dev/null)
endif

ifneq ($(TOPLEVEL_LANG),verilog)

$(COCOTB_RESULTS_FILE):
	@echo "Skipping simulation as only Verilog top level is supported on simulator=$(SIM)"

else

ifeq (, $(CMD))
    $(error Unable to locate command >$(CMD_BIN)<)
endif

ifdef WAVES
    WAVE_ARG := -waves $(WAVES)
else
    WAVE_ARG :=
endif

ifneq ($(VHDL_SOURCES),)
	SV = -sv
endif

#------------------------------------------------------------------------------------
#------------- Setting Flag for Verilog/VHDL Precompiled Librares -------------------
#------------------------------------------------------------------------------------
ifneq ($(filter PRECOMPILED_LIB_LOC_%,$(.VARIABLES)),)
    PRECOMPILED_LIBS := 1
endif

#------------------------------------------------------------------------------------
#------------- Setting Flag for Verilog/VHDL Library Compile ------------------------
#------------------------------------------------------------------------------------
ifneq ($(filter VERILOG_LIB_SOURCES_%,$(.VARIABLES)),)
    VERILOG_LIB_COMPILE := 1
endif

ifneq ($(filter VHDL_LIB_SOURCES_%,$(.VARIABLES)),)
    VHDL_LIB_COMPILE := 1
endif

#------------------------------------------------------------------------------------
# Generate -L args for all VHDL and Verilog libraries compiled by cocotb, for elaboration and run.
#------------------------------------------------------------------------------------
LIB_SEARCH_ARGS  = $(foreach LIB, $(VHDL_LIB_ORDER),    -L $(LIB))
LIB_SEARCH_ARGS += $(foreach LIB, $(VERILOG_LIB_ORDER), -L $(LIB))
LIB_SEARCH_ARGS += $(foreach LIB, $(PRECOMPILED_LIB_ORDER), -L $(LIB))

#------------------------------------------------------------------------------------
#-------------- Setting Flag for Verilog/VHDL Design Compile ------------------------
#------------------------------------------------------------------------------------
ifneq ($(filter VERILOG_SOURCES_%,$(.VARIABLES)),)
    VERILOG_DESIGN_COMPILE := 1
endif

ifneq ($(filter VHDL_SOURCES_%,$(.VARIABLES)),)
    VHDL_DESIGN_COMPILE := 1
endif

WORK = work.
BPSIM_WORK = bpsim_work

TOPMODULE_ARG = -top $(WORK)$(call deprecate,TOPLEVEL,COCOTB_TOPLEVEL)

# FP COMMON_ARGS = -nc -l bpsim.log -work $(SIM_BUILD)
# FP COMMON_ARGS = -nc -l bpsim.log -work $(SIM_BUILD)/$(BPSIM_WORK)
COMMON_ARGS = -nc -l bpsim.log

# FP BPSIM_ARGS = $(COMMON_ARGS) -pli_lib $(shell cocotb-config --lib-name-path vpi bpsim) -lib work +acc+rwcbfsWF
BPSIM_ARGS = $(COMMON_ARGS) -work $(SIM_BUILD)/$(BPSIM_WORK) -pli_lib $(shell cocotb-config --lib-name-path vpi bpsim) -lib work +acc+rwcbfsWF

COMP_ARGS = $(COMMON_ARGS) $(SV) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)

# FP GENIMAGE_ARGS = $(COMMON_ARGS) -genimage image $(LIB_SEARCH_ARGS) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)
GENIMAGE_ARGS = $(COMMON_ARGS) -work $(SIM_BUILD)/$(BPSIM_WORK) -genimage image $(LIB_SEARCH_ARGS) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)

RUN_ARGS = $(BPSIM_ARGS) -image image $(LIB_SEARCH_ARGS) $(WAVE_ARG)
VHDL_COMP_ARGS = $(COMMON_ARGS) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)

# Args for compiling named Verilog libraries: omit -work from COMMON_ARGS to avoid duplicates
VERILOG_LIB_COMP_ARGS = -nc -l bpsim.log $(SV) -timescale $(COCOTB_HDL_TIMEUNIT)/$(COCOTB_HDL_TIMEPRECISION)

#------------------------------------------------------------------------------------
#-------- Macro definitions for Verilog/VHDL Precompiled Libraries existence checks --
#------------------------------------------------------------------------------------
define CheckPreCompiledLibs
	$(foreach LIB, $(PRECOMPILED_LIB_ORDER), \
		$(if $(PRECOMPILED_LIB_LOC_$(LIB)),,$(error PRECOMPILED_LIB_LOC_$(LIB)` is empty or undefined, but '$(LIB)' is present in PRECOMPILED_LIB_ORDER)))
	$(foreach LIB_VAR, $(filter PRECOMPILED_LIB_ORDER_%, $(.VARIABLES)), \
		$(eval _VLIB := $(patsubst PRECOMPILED_LIB_ORDER_%,%,$(LIB_VAR))) \
		$(if $(filter $(_VLIB), $(PRECOMPILED_LIB_ORDER)),,$(error $(_VLIB) has PRECOMPILED_LIB_LOC set but is not listed in PRECOMPILED_LIB_ORDER)))
endef

#------------------------------------------------------------------------------------
#-------- Macro definitions for Verilog/VHDL Library source files existence checks --
#------------------------------------------------------------------------------------
define CheckVerilogLibSources
	$(foreach LIB, $(VERILOG_LIB_ORDER), \
		$(if $(VERILOG_LIB_SOURCES_$(LIB)),,$(error VERILOG_LIB_SOURCES_$(LIB) is empty or undefined, but '$(LIB)' is present in VERILOG_LIB_ORDER)))
	$(foreach SOURCES_VAR, $(filter VERILOG_LIB_SOURCES_%, $(.VARIABLES)), \
		$(eval _VLIB := $(patsubst VERILOG_LIB_SOURCES_%,%,$(SOURCES_VAR))) \
		$(if $(filter $(_VLIB), $(VERILOG_LIB_ORDER)),,$(error $(_VLIB) has VERILOG_LIB_SOURCES set but is not listed in VERILOG_LIB_ORDER)))
endef

define CheckVhdLibSources
	$(foreach LIB, $(VHDL_LIB_ORDER), \
		$(if $(VHDL_LIB_SOURCES_$(LIB)),,$(error VHDL_LIB_SOURCES_$(LIB) is empty or undefined, but '$(LIB)' is present in VHDL_LIB_ORDER)))
	$(foreach SOURCES_VAR, $(filter VHDL_LIB_SOURCES_%, $(.VARIABLES)), \
		$(eval _VLIB := $(patsubst VHDL_LIB_SOURCES_%,%,$(SOURCES_VAR))) \
		$(if $(filter $(_VLIB), $(VHDL_LIB_ORDER)),,$(error $(_VLIB) has VHDL_LIB_SOURCES set but is not listed in VHDL_LIB_ORDER)))
endef
#------------------------------------------------------------------------------------
#-------- Macro definitions for Verilog/VHDL Libraries Compile and Mapping ----------
#------------------------------------------------------------------------------------
# Compile a named VHDL library from VHDL_SOURCES_$(LIB) into $(SIM_BUILD)/$(LIB).
# Usage: $(foreach LIB, $(VHDL_LIB_ORDER), $(vhdl_CompileVhdLibs))
#
define CompileVerLibs
	$(SIM_CMD_PREFIX) $(V_COMP) $(VERILOG_LIB_COMP_ARGS) -lib $(LIB) -work $(SIM_BUILD)/$(LIB) $(EXTRA_ARGS) $(VERILOG_LIB_SOURCES_$(LIB))
endef

define MapVerLibs
	$(SIM_CMD_PREFIX) bplib -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib $(LIB) $(SIM_BUILD)/$(LIB)
endef

define CompileVhdLibs
#        $(SIM_CMD_PREFIX) bplib -work $(SIM_BUILD)/$(1) 
        $(foreach DEP,$(VHDL_LIB_DEPENDENCY_$(1)),$(call MapVhdDepLibs,$(1),$(DEP));)
	$(SIM_CMD_PREFIX) $(VHDL_COMP) $(VHDL_COMP_ARGS) -lib $(1) -work $(SIM_BUILD)/$(1) $(EXTRA_ARGS) $(VHDL_LIB_SOURCES_$(1))
endef

define MapVhdDepLibs
	$(SIM_CMD_PREFIX) bplib -nc -work $(SIM_BUILD)/$(1) map -lib $(2) $(SIM_BUILD)/$(2)
endef

define MapVhdLibs
	$(SIM_CMD_PREFIX) bplib -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib $(LIB) $(SIM_BUILD)/$(LIB)
endef
#----------------------------------------------------------------------------------------------------
# FP define CompileVhdLibs
# FP 	$(SIM_CMD_PREFIX) $(VHDL_COMP) $(VHDL_COMP_ARGS) -lib $(LIB) -work $(SIM_BUILD)/$(LIB) $(EXTRA_ARGS) $(VHDL_SOURCES_$(LIB))
# FP endef
#
# Map a compiled VHDL library into the bpsim workspace so it can be found at elaboration.
# Usage: $(foreach LIB, $(VHDL_LIB_ORDER), $(MapVhdLibs))
# FP define MapVhdLibs
# FP 	$(SIM_CMD_PREFIX) bplib -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib $(LIB) $(SIM_BUILD)/$(LIB)
# FP endef
#
# Compile a named Verilog library from VERILOG_SOURCES_$(LIB) into $(SIM_BUILD)/$(LIB).
# Usage: $(foreach LIB, $(VERILOG_LIB_ORDER), $(CompileVerLibs))
# FP define CompileVerLibs
# FP 	$(SIM_CMD_PREFIX) $(V_COMP) $(VERILOG_LIB_COMP_ARGS) -lib $(LIB) -work $(SIM_BUILD)/$(LIB) $(EXTRA_ARGS) $(VERILOG_SOURCES_$(LIB))
# FP endef

# Map a compiled Verilog library into the bpsim workspace so it can be found at elaboration.
# Usage: $(foreach LIB, $(VERILOG_LIB_ORDER), $(MapVerLibs))
# FP define MapVerLibs
# FP 	$(SIM_CMD_PREFIX) bplib -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib $(LIB) $(SIM_BUILD)/$(LIB)
# FP endef

$(SIM_BUILD)/image.so: $(VHDL_SOURCES) $(VERILOG_SOURCES) $(CUSTOM_COMPILE_DEPS) | $(SIM_BUILD)

#------------------------------------------------------------------------------------
#--------------------------- Check VHDL_LIB_SOURCES_*  ------------------------------
#------------------------------------------------------------------------------------
# Make sure all libs in VHDL_SOURCES_* are mentioned in VHDL_LIB_ORDER and vice versa
ifneq ($(VHDL_LIB_COMPILE),)
	@echo "---------------------FP1 --B4 CheckVhdlLibSources"
	$(foreach LIB, $(VHDL_LIB_ORDER), $(CheckVhdLibSources))
	@echo "---------------------FP2 -- Aft CheckVhdlLibSources"
endif

#------------------------------------------------------------------------------------------
#--------------------------- Check VERILOG_LIB_SOURCES_*  ---------------------------------
#------------------------------------------------------------------------------------------
# Make sure all libs in VERILOG_SOURCES_* are mentioned in VERILOG_LIB_ORDER and vice versa
ifneq ($(VERILOG_LIB_COMPILE),)
	$(foreach LIB, $(VERILOG_LIB_ORDER), $(CheckVerilogLibSources))
endif
#
#
# -- FP to check if these lines are now needed ?
#
	@echo "FP -- after check vhdl sources"
# FP	$(foreach SOURCES_VAR, $(filter VHDL_SOURCES_%, $(.VARIABLES)), $(check_lib_order))
#FP	# Make sure all libs in VERILOG_SOURCES_* are mentioned in VERILOG_LIB_ORDER and vice versa
#FP	$(foreach LIB, $(VERILOG_LIB_ORDER), \
#FP		$(if $(VERILOG_SOURCES_$(LIB)),,$(error VERILOG_SOURCES_$(LIB) is empty or undefined, but '$(LIB)' is present in VERILOG_LIB_ORDER)))
#FP	$(foreach SOURCES_VAR, $(filter VERILOG_SOURCES_%, $(.VARIABLES)), \
#FP		$(eval _VLIB := $(patsubst VERILOG_SOURCES_%,%,$(SOURCES_VAR))) \
#FP		$(if $(filter $(_VLIB), $(VERILOG_LIB_ORDER)),,$(error $(_VLIB) has VERILOG_SOURCES set but is not listed in VERILOG_LIB_ORDER)))
#FP	# Compile VHDL libraries in dependency order, then map each into the workspace

#------------------------------------------------------------------------------------
#---------------------- Compiling and Mapping Vhdl Libraries ------------------------
#------------------------------------------------------------------------------------
ifneq ($(VHDL_LIB_COMPILE),)
	$(file > $(SIM_BUILD)/CompileVhdLibs.log, $(foreach LIB,$(VHDL_LIB_ORDER),$(call CompileVhdLibs,$(LIB))))
	@echo "---------------------FP -- before"
	$(foreach LIB,$(VHDL_LIB_ORDER),$(call CompileVhdLibs,$(LIB));)
	@echo "FP -- after"

endif
#------------------------------------------------------------------------------------
#---------------------- Mapping Vhdl Libraries to work area -------------------------
#------------------------------------------------------------------------------------
	$(foreach LIB, $(VHDL_LIB_ORDER), $(MapVhdLibs);)

#------------------------------------------------------------------------------------
#------------------- Compiling and Mapping Verilog Libraries ------------------------
#------------------------------------------------------------------------------------
ifneq ($(VERILOG_LIB_COMPILE),)
	@echo "FP1 -- befire check vhdl lib compile"
	$(file > $(SIM_BUILD)/CompileVerLibs.log, $(foreach LIB, $(VERILOG_LIB_ORDER), $(CompileVerLibs)))
	$(foreach LIB, $(VERILOG_LIB_ORDER), $(CompileVerLibs);)
endif
#------------------------------------------------------------------------------------
#------------- generate logfile for Mapping Verilog Libraries  ----------------------
#------------------------------------------------------------------------------------
ifneq ($(VERILOG_LIB_COMPILE),)
	$(file > $(SIM_BUILD)/MapVerLibs.log, $(foreach LIB, $(VERILOG_LIB_ORDER), $(MapVerLibs)))
	$(foreach LIB, $(VERILOG_LIB_ORDER), $(MapVerLibs);)
# FP	bplib -work $(SIM_BUILD)/$(BPSIM_WORK) map -lib my_vlib $(SIM_BUILD)/my_vlib
	@echo "FP -- afer ver lib map"
endif

ifneq ($(VHDL_SOURCES),)
	@echo "FP -- Befire VHDL_COMP"
	$(SIM_CMD_PREFIX) $(VHDL_COMP) $(VHDL_COMP_ARGS) -work $(SIM_BUILD)/$(BPSIM_WORK) $(EXTRA_ARGS) $(VHDL_SOURCES)
	@echo "FP -- After VHDL_COMP"
#FP 	$(SIM_CMD_PREFIX) bplib map -lib work $(SIM_BUILD)/$(BPSIM_WORK)
#	No need for mapping since there is no vhdl lib created for just vhdl sources 
#	@echo "FP -- After bplib map"
endif
	@echo "FP -- before VL_COMP"
# FP	$(SIM_CMD_PREFIX) $(V_COMP) $(COMP_ARGS) $(EXTRA_ARGS) $(VERILOG_SOURCES)
	$(SIM_CMD_PREFIX) $(V_COMP) $(COMP_ARGS) -work $(SIM_BUILD)/$(BPSIM_WORK) $(EXTRA_ARGS) $(VERILOG_SOURCES)
	@echo "FP -- After VL_COMP"
#------------------------------------------------------------------------------------
#----------------------- generate image file image.so   -----------------------------
#------------------------------------------------------------------------------------
	$(file > $(SIM_BUILD)/GenImage.log, $(SIM_CMD_PREFIX) $(CMD) $(GENIMAGE_ARGS) $(TOPMODULE_ARG) $(EXTRA_ARGS))
	$(SIM_CMD_PREFIX) $(CMD) $(GENIMAGE_ARGS) $(TOPMODULE_ARG) $(EXTRA_ARGS)
GPI_USERS ?= $(shell cocotb-config --libpython);$(shell cocotb-config --pygpi-entry-point)
$(COCOTB_RESULTS_FILE): $(SIM_BUILD)/image.so $(CUSTOM_SIM_DEPS)
	$(RM) $(COCOTB_RESULTS_FILE)
	COCOTB_TEST_MODULES=$(call deprecate,MODULE,COCOTB_TEST_MODULES) \
	COCOTB_TESTCASE=$(call deprecate,TESTCASE,COCOTB_TESTCASE) \
	COCOTB_TEST_FILTER=$(COCOTB_TEST_FILTER) \
	COCOTB_TOPLEVEL=$(call deprecate,TOPLEVEL,COCOTB_TOPLEVEL) \
	GPI_EXTRA=$(GPI_EXTRA) \
	GPI_USERS="$(GPI_USERS)" \
	TOPLEVEL_LANG=$(TOPLEVEL_LANG) \
	$(SIM_CMD_PREFIX) $(CMD) $(RUN_ARGS) $(TOPMODULE_ARG) $(EXTRA_ARGS)
	$(call check_results)

#------------------------------------------------------------------------------------
#--------------------- generate Simulation.log file    -----------------------------
#------------------------------------------------------------------------------------
	$(file > $(SIM_BUILD)/Simulation.log, $(SIM_CMD_PREFIX) $(CMD) $(RUN_ARGS) $(TOPMODULE_ARG) $(EXTRA_ARGS))
endif
