# Copyright cocotb contributors
# Copyright (c) 2013 Potential Ventures Ltd
# Copyright (c) 2013 SolarFlare Communications Inc
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause


# Identical to Questa with the compat flow.
include $(COCOTB_MAKEFILES_DIR)/simulators/Makefile.questa-compat
