# Python environment and dependencies to build the documentation

name: cocotb-docs
dependencies:
  - python=3.8
  - pip
  # Packages installed from PyPI
  - pip:
      - ./_vendor/domaintools
      - -r requirements.txt
