# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

#
# DO NOT RENAME THIS FILE!
# PyPi uploads use OIDC, aka Trusted Publishing, to avoid the need for API keys.
# https://pypi.org/manage/project/cocotb/settings/publishing/ is configured to
# allow uploads from the cocotb GitHub project and this exact file name.
#

name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: ${{ !(contains(github.ref, 'release/') || contains(github.ref, 'master')) }}

on:
  # Run this workflow on every push to master or to a stable branch.
  push:
    branches:
      - master
      - "stable/**"
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build_release:
    name: Build release artifacts
    uses: ./.github/workflows/build-release.yml

  # This tests both the sdist and wheel builds in separate venvs back to back with just the pytest tests.
  test_release:
    name: Regression Tests
    needs: build_release
    uses: ./.github/workflows/regression-tests.yml
    with:
      test_task: release_test
      download_artifacts: true
      group: ci-free

  test_release_licensed:
    name: Regression Tests
    needs: build_release
    uses: ./.github/workflows/regression-tests.yml
    with:
      test_task: release_test
      download_artifacts: true
      group: ci-licensed

  deploy_pypi:
    name: Deploy to pypi.org
    needs:
    - test_release
    - test_release_licensed
    permissions:
      id-token: write
    runs-on: ubuntu-22.04
    # Only upload tagged releases.
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: "3.12"
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        path: dist
        pattern: cocotb-dist-*
        merge-multiple: true
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
      # Authentication to PyPi is done through OIDC ("Trusted Publishing").
