# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: ${{ !(contains(github.ref, 'release/') || contains(github.ref, 'master')) }}

on:
  # Run this workflow on every push to the master branch, or a stable branch.
  push:
    branches:
      - master
      - "stable/**"
      - "feature/**"
  pull_request:
    branches:
      - master
      - 'stable/**'
      - 'feature/**'

jobs:
  changes:
    uses: ./.github/workflows/detect-changes.yml

  test_dev:
    needs: changes
    if: needs.changes.outputs.run_tests == 'true'
    name: Regression Tests
    uses: ./.github/workflows/regression-tests.yml
    with:
      test_task: dev_test
      collect_coverage: true
      group: ci-free

  test_dev_licensed:
    needs: changes
    if: github.repository == 'cocotb/cocotb' && needs.changes.outputs.run_tests == 'true'
    name: Regression Tests
    uses: ./.github/workflows/regression-tests.yml
    with:
      test_task: dev_test
      collect_coverage: true
      group: ci-licensed
