# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# Run tests against an extended set of simulator (versions).

name: Test extended tool versions

on:
  # Run every Sunday at 2am (UTC).
  schedule:
    - cron: '0 2 * * 0'
  # Allow triggering a CI run from the web UI.
  workflow_dispatch:

jobs:
  test_dev:
    if: github.repository == 'cocotb/cocotb'
    name: Regression Tests
    uses: ./.github/workflows/regression-tests.yml
    with:
      nox_session_test_sim: dev_test_sim
      nox_session_test_nosim: dev_test_nosim
      group: extended
      max_parallel: 5
