# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

name: "Update pre-commit hooks"

on:
  schedule:
  - cron: "00 03 * * *"

jobs:
  update-pre-commit-hooks:
    name: Update pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Update pre-commit hooks
      run: |
        pip install pre-commit
        pre-commit autoupdate
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        commit-message: "Update pre-commit hooks"
        branch: update-pre-commit
        title: "Update pre-commit hooks"
        body: |
          Update pre-commit hooks to most recent versions
        reviewers: |
          cocotb/maintainers
