# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

name: Publish to PyPi

on:
  push:
    branches:
      - master
      - 'stable/**'
    tags:
      - 'v*'

jobs:
  pypi-upload:
    runs-on: ubuntu-latest
    name: deploy
    steps:
    - uses: actions/checkout@master
      with:
        # To generate a valid version number setuptools_scm needs sufficient
        # git history.
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a source tarball
      run: >-
        python -m
        build
        --sdist
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
